server:
  port: 9000
spring:
  security:
    oauth2:
      authorization-server:
        issuer: issuer-j
  # test?
  jwt:
    keystore:
      location: classpath:jwt-jstudy.jks
      password: changeit
      key-alias: jwt-jstudy
      key-password: changeit